app/models.py
from . import db 
from app import login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))




class User(UserMixin,db.Model):
    __tablename__='users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index=True,unique = True)
    pass_secure = db.Column(db.String(255))
    comment = db.relationship('Comments',backref='user',lazy='dynamic')
    post = db.relationship('Post',backref='user',lazy='dynamic')
    email=db.Column(db.String(255),unique = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())


    @login_manager.user_loader
    def get_user(user_id):
        return User.query.get(user_id)



    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)


    def __repr__(self):
        return f'User {self.username}'

    def __repr__(self):
        return f'User{self.username}'

class Post(db.Model):
    __tablename__='posts'
    id=db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    age = db.Column(db.String(255))
    gender = db.Column(db.String(255))
    description = db.Column(db.String(255))
    comment = db.relationship('Comments',backref='post',lazy='dynamic')
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    def save(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_posts(id):
        posts = Post.query.order_by(post_id = id).desc().all()
        return posts
    
    def __repr__(self):
        return f'Post {self.category}'

class Comments(db.Model):
    __tablename__='comments'
    id=db.Column(db.Integer,primary_key=True)
    comment=db.Column(db.String(255))
    name=db.Column(db.String(255))
    number=db.Column(db.String(255))
    user_id=db.Column(db.Integer,db.ForeignKey('users.id'))
    post_id=db.Column(db.Integer,db.ForeignKey('posts.id'))
    def save(self):
        db.session.add(self)
        db.session.commit()
    def __repr__(self):
        return f'Comments {self.comment}'

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,BooleanField,TextAreaField,RadioField
from wtforms.validators import Required
from wtforms import ValidationError

class PostForm(FlaskForm):
    name = StringField('Name',validators=[Required()])
    age = StringField('Age', validators = [Required()])
    gender = RadioField('Gender',choices=[('Male','Male'),('Female','Female')])
    description = TextAreaField('Write more information',validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    name =StringField('Name',validators=[Required()])
    number = StringField('Your Number',validators=[Required()])
    comment = TextAreaField('Enter a good description', validators=[Required()])
    Submit = SubmitField('Submit')


class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
db = SQLAlchemy()
mail = Mail()
bootstrap = Bootstrap()

photos = UploadSet('photos',IMAGES)


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config_options[config_name])
    
    from  app.auth import auth as auth_blueprint
    from app.main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

      # configure UploadSet
    configure_uploads(app,photos)


    return app

app/main/__init__.py
from flask import Blueprint 

main =  Blueprint('main',__name__)

from . import views

app/main/views.py
from . import main
from app.models import Post,Comments
from . forms import PostForm,CommentForm
from flask_login import login_required, current_user, login_manager
from flask import render_template,request,redirect,url_for,abort
from ..models import User
from .forms import UpdateProfile
from .. import db,photos
from app.main import main





@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    all_posts = Post.query.all()
    return render_template('home.html',all_posts = all_posts)


@main.route('/posts/new',methods=['GET','POST'])
@login_required
def new_post():
    post_form = PostForm()
    if post_form.validate_on_submit():
        user_id = current_user._get_current_object().id
        post = Post(name = post_form.name.data,age = post_form.age.data,gender = post_form.gender.data,description = post_form.description.data,user_id=user_id)
        post.save()
        return redirect(url_for('main.index'))
    return render_template('post.html',post_form=post_form)

@main.route('/comment/<int:post_id>',methods=['GET','POST'])

@login_required
def comment(post_id):
    comment_form = CommentForm()
    comments = Comments.query.filter_by(post_id=post_id).all()
    if comment_form.validate_on_submit():
        post_id = post_id
        user_id = current_user._get_current_object().id
        comment = Comments(name = comment_form.name.data,number = comment_form.number.data,comment = comment_form.comment.data,user_id = user_id, post_id = post_id) 
        comment.save()
        return redirect(url_for('main.index'))
    return render_template('comment.html',comment_form=comment_form,comments = comments)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template("profile/profile.html",user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)    


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

        return redirect(url_for('main.profile',uname=uname))
    
    return render_template('home.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Barlow|Crimson+Text|EB+Garamond|Merriweather&display=swap"
        rel="stylesheet">
    <!-- cdn links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/css/mdb.min.css" rel="stylesheet">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/css/uikit.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title%}
    <title>Connect-me - {{ title }}</title>
    {% else%}
    <title>Connect-me</title>
    {% endif%}
</head>

<body>

    {% block content%}

    {% endblock%}



    <!-- scripts -->
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.10/js/mdb.min.js"></script>
    <!-- UIkit JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.2.0/js/uikit-icons.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}

    {{wtf.quick_form(comment_form)}}

    {% for comment in comments %}
        {{comment.name}}
        {{comment.number}}
        {{comment.comment}}
    {% endfor %}

{% endblock %}

app/templates/index.html
{% extends 'base.html'%}

{% block content%}


<div class="uk-position-relative">
    <div class="uk-height-large uk-flex uk-flex-center uk-flex-middle uk-background-cover uk-dark"
        data-src="https://i.ibb.co/gPXPBnz/Be-Funky-photo-23.jpg" style="height: 610px" uk-img
        uk-scrollspy="cls: uk-animation-kenburns; repeat: true">
        <a class="uk-position-absolute uk-transform-center" style="left: 20%; top: 30%" href="#" uk-marker></a>
        <a class="uk-position-absolute uk-transform-center" style="left: 60%; top: 40%" href="#" uk-marker></a>
        <a class="uk-position-absolute uk-transform-center" style="left: 80%; top: 70%" href="#" uk-marker></a>
        <h1 class="uk-animation-slide-bottom" style="font-family: 'Barlow', sans-serif; font-size: 50px; color: beige">
            Connect-me</h1>
    </div>
    <div class="uk-position-top">
        <nav class="uk-navbar-container uk-navbar-transparent" uk-navbar>
            <div class="uk-navbar-left" style="margin-left: 3%">
                <ul class="uk-navbar-nav">
                    <li class="uk-active"><a href="#">
                            <p class="uk-text-bold  uk-animation-slide-left"
                                style="font-family:'Crimson Text', serif; font-size: 20px">

                                <i class="fas fa-binoculars"></i>
                                Connect-me</p>
                        </a></li>
                    <li><a href="#">
                            <button class="ui black basic button">Item</button>
                        </a></li>
                    <li><a href="#">
                            <button class="ui black basic button" type="button"
                                uk-toggle="target: #offcanvas-flip">About</button>

                            <div id="offcanvas-flip" uk-offcanvas="flip: true; overlay: true">
                                <div class="uk-offcanvas-bar">

                                    <button class="uk-offcanvas-close" type="button" uk-close></button>

                                    <h3>Connect-me</h3>

                                    <p> If a person is missing, get to sign up and login in to the web page and upload
                                        the missing person and the details in which users logged in can comment and
                                        provide additional information on the whereabouts of the missing person if
                                        known.</p>

                                    <blockquote cite="#">
                                        <p class="uk-margin-small-bottom">There is no exercise better for the heart than
                                            reaching down and lifting people up..</p>
                                        <footer>By the <cite><a href="#">Connect-me Team</a></cite></footer>
                                    </blockquote>

                                </div>
                            </div>

                        </a>
                    </li>
                </ul>
                <ul class="uk navbar-nav">
                    <li style="margin-left: 620%">
                        <a href="#">
                            <button class="ui black basic button  uk-animation-slide-right">Services</button>

                            <div uk-dropdown="animation: uk-animation-slide-top-small; duration: 1000">
                                <ul class="uk-nav uk-dropdown-nav">
                                    <li class="uk-nav-er">Proceed to:</li>
                                    <li>
                                        <!-- This is an anchor toggling the modal -->
                                        <a href="#" uk-toggle>login</a>

                                        <!-- This is the modal -->
                                        <div id="modal-example" uk-modal>
                                            <div class="uk-modal-dialog uk-modal-body">
                                                <section class="form-gradient">

                                                    <!--Form with header-->
                                                    <div class="card">

                                                        <!--Header-->
                                                        <div class="header pt-3 peach-gradient">

                                                            <div class="row d-flex justify-content-center">
                                                                <h3 class="white-text mb-3 pt-3 font-weight-bold">Log in
                                                                </h3>
                                                            </div>

                                                            <div class="row mt-2 mb-3 d-flex justify-content-center">
                                                                <!--Facebook-->
                                                                <a class="fa-lg p-2 m-2 fb-ic"><i
                                                                        class="fab fa-facebook-f white-text fa-lg">
                                                                    </i></a>
                                                                <!--Twitter-->
                                                                <a class="fa-lg p-2 m-2 tw-ic"><i
                                                                        class="fab fa-twitter white-text fa-lg">
                                                                    </i></a>
                                                                <!--Google +-->
                                                                <a class="fa-lg p-2 m-2 gplus-ic"><i
                                                                        class="fab fa-google-plus-g white-text fa-lg">
                                                                    </i></a>
                                                            </div>

                                                        </div>
                                                        <!--Header-->

                                                        <div class="card-body mx-4 mt-4">

                                                            <!--Body-->
                                                            <div class="md-form">
                                                                <input type="text" id="Form-email3"
                                                                    class="form-control">
                                                                <label for="Form-email3">Your email</label>
                                                            </div>

                                                            <div class="md-form pb-1 pb-md-3">
                                                                <input type="password" id="Form-pass3"
                                                                    class="form-control">
                                                                <label for="Form-pass3">Your password</label>
                                                                <p
                                                                    class="font-small grey-text d-flex justify-content-end">
                                                                    Forgot <a href="#"
                                                                        class="dark-grey-text ml-1 font-weight-bold">
                                                                        Password?</a></p>
                                                            </div>


                                                            <!--Grid row-->
                                                            <div class="row d-flex align-items-center mb-4">

                                                                <!--Grid column-->
                                                                <div class="col-md-1 col-md-5 d-flex align-items-start">
                                                                    <div class="text-center">
                                                                        <button type="button"
                                                                            class="btn btn-grey btn-rounded z-depth-1a">Log
                                                                            in</button>
                                                                    </div>
                                                                </div>
                                                                <!--Grid column-->

                                                                <!--Grid column-->
                                                                <div class="col-md-7">
                                                                    <p
                                                                        class="font-small grey-text d-flex justify-content-end mt-3">
                                                                        Don't have an account? <a href="#"
                                                                            class="dark-grey-text ml-1 font-weight-bold">
                                                                            Sign up</a></p>
                                                                </div>
                                                                <!--Grid column-->

                                                            </div>
                                                            <!--Grid row-->
                                                        </div>

                                                    </div>
                                                    <!--/Form with header-->

                                                </section>
                                            </div>
                                        </div>
                                    </li>
                                    <li>


                                        <!-- This is an anchor toggling the modal -->
                                        <a href="#modal-example" uk-toggle>Open</a>

                                        <!-- This is the modal -->
                                        <div id="modal-example" uk-modal>
                                            <div class="uk-modal-dialog uk-modal-body">
                                                <h2 class="uk-modal-title">Headline</h2>
                                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                    eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
                                                    ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
                                                    aliquip ex ea commodo consequat. Duis aute irure dolor in
                                                    reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                                                    pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
                                                    culpa qui officia deserunt mollit anim id est laborum.</p>
                                                <p class="uk-text-right">
                                                    <button class="uk-button uk-button-default uk-modal-close"
                                                        type="button">Cancel</button>
                                                    <button class="uk-button uk-button-primary"
                                                        type="button">Save</button>
                                                </p>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="uk-nav-divider"></li>

                                </ul>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>



{% for post in all_posts %}
{{post.name}}
{{post.age}}
{{post.gender}}
{{post.description}}
{% endfor %}


{% endblock %}

app/templates/post.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="js-upload" uk-form-custom>
    <input type="file" multiple>
    <button class="uk-button uk-button-default" type="button" tabindex="-1">Select Picture</button>
</div>

    {{wtf.quick_form(post_form)}}

{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying username -->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!-- displaying user bio -->
            {% if user.bio%}
            <p> {{user.bio}}</p>
            {% else %}
            <p> {{ user.username| capitalize }} has no bio </p>
            {% endif %}
        </div>

        <!-- Displaying profile photo -->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{ url_for('',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
            <p> No profile picture</p>
            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method='POST' enctype= "multipart/form-data" >
            
            <input type="file" name="photo" class="form-control" required>
            <input type="submit">
            </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock%}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}